version: '3.8'
services:
  mysql-master:
    image: mysql:5.7
    container_name: mysql-master
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_REPLICATION_USER: repl_user
      MYSQL_REPLICATION_PASSWORD: repl_pass
      MYSQL_DATABASE: imdb_db
    ports:
      - "3307:3306"
    command: ["mysqld"]
    volumes:
      - master_data:/var/lib/mysql
      - ./master_my.cnf:/etc/mysql/my.cnf
      - ./scripts:/home/scripts
      - ./data:/home/data
      - ./title.basics.tsv:/var/lib/mysql-files # Correct mount: mount the directory
    # entrypoint: ["/bin/bash", "-c", "chown mysql:mysql /etc/mysql/my.cnf && chmod 600 /etc/mysql/my.cnf && exec mysqld"]
    networks:
      - mysql-network

  mysql-slave1:
    image: mysql:5.7
    container_name: mysql-slave1
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_REPLICATION_USER: repl_user
      MYSQL_REPLICATION_PASSWORD: repl_pass
    ports:
      - "3308:3306"
    command: ["mysqld"]
    volumes:
      - slave1_data:/var/lib/mysql
      - ./slave1_my.cnf:/etc/mysql/my.cnf
    # entrypoint: ["/bin/bash", "-c", "chown mysql:mysql /etc/mysql/my.cnf && chmod 600 /etc/mysql/my.cnf && exec mysqld"]
    networks:
      - mysql-network

networks:
  mysql-network:
volumes:
  master_data:
  slave1_data:
