version: '3.8'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: imdb_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data_test:/var/lib/mysql
      - ./scripts:/home/scripts
      - ./data:/home/data

volumes:
  db_data_test: